version: '3.9'

services:

  db:
    image: postgres:16.1-alpine3.19
    restart: on-failure
    env_file:
      - ./env_vars/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"